language: java
dist: trusty
sudo: required
services:
  - docker
jdk:
  - oraclejdk8

env:
  global:
    - EMBULK_INPUT_POSTGRESQL_TEST_CONFIG=$TRAVIS_BUILD_DIR/ci/postgresql.yml
    - EMBULK_INPUT_MYSQL_TEST_CONFIG=$TRAVIS_BUILD_DIR/ci/mysql.yml
cache:
  directories:  # run "travis cache --delete" to delete caches
    - $HOME/.gradle

before_script:
  - docker-compose up -d
  - docker-compose ps

script:
  - ./gradlew --info check
